# Configuration for Alacritty, the GPU enhanced terminal emulator.

import:
  - ~/.config/alacritty/themes/ayu_dark.yaml

env:
  TERM: screen-256color

window:
  opacity: 0.75
  padding:
    x: 14
    y: 10
  dynamic_padding: false
  decorations: buttonless

font:
  normal:
    family: "VictorMono Nerd Font"
    style: SemiBold
  bold:
    family: "VictorMono Nerd Font"
    style: Bold
  italic:
    family: "VictorMono Nerd Font"
    style: SemiBold Italic
  bold_italic:
    family: "VictorMono Nerd Font"
    style: Bold Italic
  size: 17.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 2
    y: 1
  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0

  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina you
  # probably want this set to false.
  #
  # macOS >= 10.14.x:
  #
  # If the font quality on non-retina display looks bad then set
  # `use_thin_strokes` to `true` and enable font smoothing by running the
  # following command:
  #   `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
  #
  # This is a global setting and will require a log out or restart to take
  # effect.
  # use_thin_strokes: true
  # defaults write -g AppleFontSmoothing -int 0

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# copy on selection
selection:
  save_to_clipboard: true

mouse:
  hide_when_typing: true

key_bindings:
  - { key: Key1, mods: Command, chars: "\x021" } # select tmux window 1
  - { key: Key2, mods: Command, chars: "\x022" } #                ... 2
  - { key: Key3, mods: Command, chars: "\x023" } #                ... 3
  - { key: Key4, mods: Command, chars: "\x024" } #                ... 4
  - { key: Key5, mods: Command, chars: "\x025" } #                ... 5
  - { key: Key6, mods: Command, chars: "\x026" } #                ... 6
  - { key: Key7, mods: Command, chars: "\x027" } #                ... 7
  - { key: Key8, mods: Command, chars: "\x028" } #                ... 8
  - { key: Key9, mods: Command, chars: "\x029" } #                ... 9
  - { key: Comma, mods: Command, chars: "\x02," } # rename the current tmux window
  - { key: E, mods: Command, chars: "\x02|" } # split tmux window vertically
  - { key: E, mods: Command|Shift, chars: "\x02-" } # split tmux window horizontally
  - { key: F, mods: Command|Shift, chars: "\x02\x5b\x2f" } # start tmux search mode
  - { key: F, mods: Command, chars: "v\n" }
  - { key: G, mods: Command, chars: "\x02g" } # open git manager 'jesseduffield/lazygit'
  - { key: J, mods: Command, chars: "\x02\x54" } # use (cmd+j) to open the session manager popup (t)
  - { key: L, mods: Command, chars: "\x02L" } # switch to the last tmux session
  - { key: O, mods: Command, chars: "lfcd\n" } # open file manager 'gokcehan/lf'
  - { key: P, mods: Command, chars: ":GoToFile\n" } # files
  - { key: P, mods: Command|Shift, chars: ":GoToCommand\n" } # commands
  - { key: T, mods: Command, chars: "\x02c" } # create a new tmux window
  - { key: U, mods: Command, chars: "\x02u" } # open URL (cmd+u)
  - { key: W, mods: Command, chars: "\x02x" } # kill the current pane
  - { key: Z, mods: Command, chars: "\x02z" } # toggle zoom state of the current tmux pane

# Live config reload (changes require restart)
live_config_reload: true
