# Colors (Monokai Pro)
colors:
  # Default colors
  primary:
    background: '#2D2A2E'
    foreground: '#FCFCFA'

  # Normal colors
  normal:
    black:   '#403E41'
    red:     '#FF6188'
    green:   '#A9DC76'
    yellow:  '#FFD866'
    blue:    '#FC9867'
    magenta: '#AB9DF2'
    cyan:    '#78DCE8'
    white:   '#FCFCFA'

  # Bright colors
  bright:
    black:   '#727072'
    red:     '#FF6188'
    green:   '#A9DC76'
    yellow:  '#FFD866'
    blue:    '#FC9867'
    magenta: '#AB9DF2'
    cyan:    '#78DCE8'
    white:   '#FCFCFA'

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic

  size: 13

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

# Live config reload (changes require restart)
live_config_reload: true
