# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Sets user-defined palette
palette = "catppuccin_mocha"

[character]
# Note the use of Catppuccin color 'maroon'
# success_symbol = "[[♥](green) ](maroon)"
# error_symbol = "[](red)"
# vicmd_symbol = "[](green)"
success_symbol = "👉"
vicmd_symbol = "✌️"
error_symbol = "🚨"


[directory]
truncation_length = 4
# Catppuccin 'lavender'
style = "bold lavender"

[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_status]
disabled = true

[aws]
disabled = true

# palette tables should be last in the config ⚓️
# https://github.com/catppuccin/starship
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
