# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "🐶"
vicmd_symbol = "🐰"
error_symbol = "🐞"

[directory]
truncation_length = 4

[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[git_branch]
disabled = false

[git_commit]
disabled = false

[git_state]
disabled = false

[git_metrics]
disabled = false

[git_status]
disabled = false

[aws]
disabled = true
