# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[](white)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[directory]
style = "blue bold"

[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_status]
disabled = true
