name: CI

on: [push, workflow_dispatch]

env:
  HOME: ${{ github.workspace }}

jobs:
  bootstrap-on-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          path: ./dotfiles

      - name: Install dotfiles
        run: $HOME/dotfiles/install.sh

  cog_check_job:
    runs-on: ubuntu-latest
    name: Check conventional commit compliance
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conventional commits check
        uses: oknozor/cocogitto-action@v3.4

  typo:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check spelling
        uses: crate-ci/typos@master
